project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "*.md"
  resources: 
    - "/images"
    - "/learn/tree-lab/Colorado-Tree-Observation-Dashboard-Handbook.pdf"
  preview: 
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true
    
format:
  html:
    theme: 
        - litera
        - styles.scss
    mainfont: Poppins

website:
  title: Discovery Arboretum
  site-url: https://www.colostate.edu/discovery-arb
  repo-url: https://github.com/danielburcham/arb-quarto-site
  google-analytics: "G-H0H6YFRLY9"
  open-graph:
    locale: en_US
  navbar:
    pinned: true
    left:
      - text: "Discover"
        menu: 
          - text: "About"
            href: discover/about/index.qmd
          - text: "History"
            href: discover/history/index.qmd
      - text: "Visit"
        href: visit/index.qmd
      - text: "Learn"
        menu:
          - text: "Events and classes"
            href: learn/events-and-classes/index.qmd
          - text: "Explore our trees"
            href: learn/explore-our-trees/index.qmd
          - text: "Tree lab"
            href: learn/tree-lab/index.qmd
      - text: "Support"
        menu: 
          - text: "Volunteer"
            href: support/volunteer/index.qmd
          - text: "Give"
            href: support/give/index.qmd
    logo: CSU-Symbol-r-357-617-RGB.png
    logo-alt: Colorado State University
    right:
      - text: "Contact"
        href: contact/index.qmd
  search:
    location: navbar
    type: textbox
  page-footer:
    background: "#1E4D2B"
    right: |
        [![](https://brand.colostate.edu/wp-content/themes/csu-theme/assets/img/csu-onleline-final.svg){fig-alt="Colorado State University"}](https://www.colostate.edu)
    left: 
        - © 2025 Colorado State University