---
title: "Visit"
format:
    html
include-in-header: 
  - text: |
      <style>figure { padding: 3em 0 3em 0; }</style
---

![The conifer collection contains a wide variety of pines, firs,
spruces, and many other conifer species.](DSCF7640.jpg){#conifers
.margin-caption}

Whether you're coming to take a stroll, rest under a leafy canopy, or
discover the beauty of trees, you are welcome to explore the arboretum
on the main campus of Colorado State University. Survey our trees using
the interactive map, take one of our tree tours, or sit and relax in one
of our tranquil landscapes.

## Hours

The arboretum is free and open during daylight hours every day.

## Parking

If you're visiting during the evenings (after 4:00 pm), weekends, or
university holidays, you can park next to the arboretum in Lot 240 at
851 W Pitkin St. Unfortunately, there is no visitor parking inside the
arboretum. The campus parking lots around the arboretum require paid
permits, and the parking rules are enforced 7:30 a.m. to 4:00 p.m.
during weekdays throughout the entire year, except for official
university holidays. If you're visiting during enforcement hours, hourly
parking is available in Lot 585 at 615 W Lake St.

## Directions to the Arboretum

The arboretum is located on main campus next to Canvas Stadium and
Summit Hall (see map below). We've already set the destination to the
arboretum. Just choose or enter your starting point! To explore other
campus locations, click [here](http://maps.colostate.edu/){.external
target="_blank"} for an interactive campus map.

```{=html}
<html>
<head>
<meta charset="utf-8">
<link href='https://api.mapbox.com/mapbox-gl-js/v3.6.0/mapbox-gl.css' rel='stylesheet' />
<script src='https://api.mapbox.com/mapbox-gl-js/v3.6.0/mapbox-gl.js'></script>
</head>
<body>
<style>
    .mapboxgl-popup {
        max-width: 400 px;
        font:
            12px/20px 'Poppins',
            Arial,
            Helvetica,
            sans-serif;
    }
</style>

<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.3.1/mapbox-gl-directions.js"></script>
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.3.1/mapbox-gl-directions.css" type="text/css">

<div id='map' style='width: 100%; height: 500px;'></div>
<script>
mapboxgl.accessToken = 'pk.eyJ1IjoiZGFuaWVsYnVyY2hhbSIsImEiOiJjbTZiOWttb2cwNjc5MnZxMmJ0aGd6ZzM3In0.2GGCvFjc3IHHxLFTKX5uuQ';

const map = new mapboxgl.Map({
    container: 'map', // container ID
    style: 'mapbox://styles/mapbox/streets-v12', // style URL
    center: [-105.092, 40.570], // starting position [lng, lat]
    zoom: 15.5, // starting zoom
});

var directions = new MapboxDirections({
        accessToken: mapboxgl.accessToken
    });

map.addControl(directions,'top-left');

map.on('load',  function() {
    directions.setDestination([-105.092, 40.570]);
})

    map.on('load', () => {
        map.addSource('places', {
            'type': 'geojson',
            'data': {
                'type': 'FeatureCollection',
                'features': [
                    {
                        'type': 'Feature',
                        'properties': {
                            'description':
                                '<strong>Parking Lot 240</strong><br>851 W Pitkin St<br>Permit parking',
                        'icon': 'parking'
                        },
                        'geometry': {
                            'type': 'Point',
                            'coordinates': [-105.0907, 40.570556]
                        }
                    },
                    {
                        'type': 'Feature',
                        'properties': {
                            'description':
                                '<strong>Parking Lot 585</strong><br>615 W Lake St<br>Hourly parking',
                        'icon': 'parking'
                        },
                        'geometry': {
                            'type': 'Point',
                            'coordinates': [-105.08825, 40.567778]
                        }
                    }
                ]
            }
        });
        // Add a layer showing the places.
        map.addLayer({
            'id': 'places',
            'type': 'symbol',
            'source': 'places',
            'layout': {
                        'icon-image': ['get','icon'],
                         'icon-allow-overlap': true
                    }
        });

        // Create a popup, but don't add it to the map yet.
        const popup = new mapboxgl.Popup({
            closeButton: false,
            closeOnClick: false
        });

        map.on('mouseenter', 'places', (e) => {
            // Change the cursor style as a UI indicator.
            map.getCanvas().style.cursor = 'pointer';

            // Copy coordinates array.
            const coordinates = e.features[0].geometry.coordinates.slice();
            const description = e.features[0].properties.description;

            // Ensure that if the map is zoomed out such that multiple
            // copies of the feature are visible, the popup appears
            // over the copy being pointed to.
            if (['mercator', 'equirectangular'].includes(map.getProjection().name)) {
                while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
                    coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
                }
            }

            // Populate the popup and set its coordinates
            // based on the feature found.
            popup.setLngLat(coordinates).setHTML(description).addTo(map);
        });

        map.on('mouseleave', 'places', () => {
            map.getCanvas().style.cursor = '';
            popup.remove();
        });
    });

</script>
</body>
</html>
```

## Visitor Guidelines

Groups and individuals visiting the arboretum should be aware of the
following rules:

-   Consistent with [University policies](https://tobaccofree.colostate.edu/){target="blank"}, smoking and vaping are prohibited on the property.

-   Removing or damaging plants or the landscape is strictly prohibited. 

-   Dogs must be leashed at all times. Owners are responsible for removal and disposal of their dogs’ waste. 

-   Bicycles and electric bicycles are permitted only on the paved bike path, at speeds of 15 miles per hour or slower. A bike rack is available just inside the south entrance off Lake St.
