---
title: "History"
format:
    html
---

In 1973, the State Board of Agriculture, the University's governing body
at the time, agreed to close the CSU Trailer Court at 850 W Lake St.
With the student population growing quickly after World War II, the
trailer court had been created in 1953 for married veterans, but the
amount of student housing had improved in subsequent years, reducing the
need for temporary, affordable homes. Like others settling in the area,
the trailer court residents had planted many fast-growing trees,
especially Siberian elm (*Ulmus pumila*), to provide shade, and the
trees had quickly grown to provide dense cover in just a few decades. In
its decision, the Board offered the same two acres to the nearby W.D.
Holley Plant and Environmental Research Center (PERC), a facility
managed by the Department of Horticulture, and Dr. Bert Swanson
petitioned for the development of a new woody plant collection on the
grounds.

![Several new student dormitories, including (left-right) Edwards,
Ellis, and Newsom Halls, can be seen in this aerial image of the CSU
main campus from February 1960. The CSU trailer court with many small,
recently-planted trees is visible on the bottom of the image. Source:
Archives & Special Collections, Colorado State
University.](UHPC_B8109N.png){#1957-aerial .lightbox width="70%"}

With an intent to trial a wide variety of trees for the area, the
department started planning and preparing for a new arboretum.
Initially, the arboretum landscape was organized by grouping plants in
botanical families. The design, common in the 19th Century, usually
encouraged comparisons along a pathway showing increasing biological
development, but the arrangement was largely chosen as a simple
organizing principle allowing students and visitors to learn about trees
in related plantings. With the design established, staff, students, and
other volunteers made some initial improvements to the grounds,
including a new storage building and driveways, and a local Army reserve
unit helped for several weekends with grading work to create subtle
mounds and surface drainage.

![In this aerial image from April 1979, the arboretum was sparsely
planted with a mix of small, new and large, existing trees retained from
the trailer court, including a row of large Siberian elms on the western
edge. Source: Archives & Special Collections, Colorado State
University.](UHPC_R4162_18A.png){#1979-aerial .lightbox width="70%"}

In 1978, students and other volunteers installed the first large batch
of new trees, and they were progressively added to the arboretum's
collection records. The labeling system developed at the time assigned a
unique identifier to individual trees for tracking, and it is still
largely used today with just a few changes. The first four digits show
the year the tree was received, and the subsequent numbers represent the
tree's order in a sequence of trees received that year. By the end of
1978, nearly 200 new trees were added to the new collection. Although
many are still growing in the arboretum today, several died, including a
Franklin tree (*Franklinia alatamaha*) and dove tree (*Davidia
involucrata*) from the U.S. National Arboretum.

Over subsequent years, the woody plant collection gradually developed
with plant material donated by many nurseries, botanic gardens, and
universities. Although the number of new trees each year declined as the
arboretum filled, over 4,000 distinct varieties of trees and shrubs were
planted and evaluated in the first 30 years. By regularly monitoring the
collection, CSU faculty and staff identified some of the most dependable
woody plants for use in regional landscapes, and the recommendations
were periodically summarized for the green industry and broader public.

For nearly 50 years, the arboretum has remained committed to its basic
purpose amid significant change. Like many other areas along the Front
Range, the developed area of Fort Collins expanded over 6.5 times
between 1940 and 2000 and hosted a ten-fold increase in the resident
population. With similar growth on the CSU campus, the land around the
arboretum was gradually developed into new housing and athletics
facilities, and the other parts of PERC, including the greenhouses and
trial gardens, moved to other locations on campus. Today, the arboretum
is a place for anyone to study and observe trees commonly found in the
region and discover unusual trees suited for western communities. As a
special campus green space, it is also a place for anyone to relax,
socialize, and enjoy the outdoors. Moving forward, we will be working to
sustain the arboretum's valuable tree collection, enhance our learning
opportunities, and broaden our engagement with the wider community.
